# Generated by Django 5.1.7 on 2025-03-14 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.IntegerField(verbose_name='شماره پرونده')),
                ('need_level', models.IntegerField(choices=[(1, 'متوسط'), (2, 'شدید'), (3, 'خیلی شدید')], default=1, verbose_name='سطح نیاز')),
                ('family_type', models.IntegerField(choices=[(1, 'یتیم'), (2, 'زندانی'), (3, 'مطلقه'), (4, 'رها شده'), (5, 'بیمار')], default=1, verbose_name='نوع نیازمندی')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کدپستی')),
                ('is_active', models.BooleanField(default=True, verbose_name='تحت پوشش')),
                ('distlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mohsenin.distlist', verbose_name='لیست توزیع')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=50, verbose_name='')),
                ('national_id', models.CharField(max_length=10, verbose_name='شماره ملی')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('is_orphan', models.BooleanField(verbose_name='یتیم')),
                ('is_guardian', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Mohsenin.family')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardianship', to='Mohsenin.person', verbose_name='سرپرست خانوار'),
        ),
    ]
